#!/usr/bin/env bash

set -e

last="${@:(($#))}"
set -- "${@:1:$(($#-1))}"

dst="${last%.zip}"
if [ "$dst" == "$last" ]; then
    echo "Usage: $0 [flags...] <file>.zip" >&2
    exit 1
fi

unzip "$@" -d "$dst" "$last"
